### ISSUE TITLE
Chatting

### ISSUE THREAD

**Issue by MohamedAli00949** [qaree-infra/qaree-backend#11]
## Service:
[socket.io](https://socket.io)

## Tasks:
- [x] Create one to one chat
- [x]  Create a query for getting messages at one-to-one
- [x] Create join to community
- [ ] Change community admin
- [ ] Add permission to admin at community
- [x] Get community details
- [x] Leave community
