### ISSUE TITLE
Track reading using current/finished reading shelves

### ISSUE THREAD

**Issue by MohamedAli00949** [qaree-infra/qaree-backend#16]
## situation 
The user can add the book to the current/finished reading shelves.

## What do we want to do?
We want to make the current reading full with the books that the user started reading or will start reading.
If the user has completed the reading the book will be moved to the finished reading shelf.

## Tasks
- [ ] Create main three shelves after creating a user with ar and en names
- [ ] Make the shelf names similar at creation
- [ ] At the reading chapter, if the progress after reading the chapter is 100 put the book on the finished reading shelf instead of current one.
- [ ] Disallow to add books to current/finished reading shelves
